#!/usr/bin/env python3
"""
gen_preview_ids.py — functions/api/preview_ids.js is a PROJECTION of the committed id map
conformance/web/preview_parity.json (D5-11, SITE-R-034): the Pages Functions read the map
at runtime through this generated ES module (no JSON import in the worker bundle).

    python3 conformance/web/gen_preview_ids.py --write   # regenerate the module
    python3 conformance/web/gen_preview_ids.py --check   # byte-compare (preview_parity.py, deploy.sh)
Deterministic (sorted keys, no timestamps). Stdlib only.
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
MAP = ROOT / "conformance" / "web" / "preview_parity.json"
OUT = ROOT / "functions" / "api" / "preview_ids.js"


def load_map():
    return json.load(open(MAP, encoding="utf-8"))


def render(doc):
    body = json.dumps(doc["preview"], indent=2, sort_keys=True, ensure_ascii=True)
    return (
        "// GENERATED by conformance/web/gen_preview_ids.py from conformance/web/preview_parity.json\n"
        "// (the add-only JS preview id map, PLAN-v3 §2.18 D5-11 / SITE-R-034). Do not edit: the parity\n"
        "// gate byte-compares this file. Each preview id -> { stage, counted, engine{version: [ids]},\n"
        "// req_ids{version: [ids]} }; `counted:false` rows render but never enter summary / badge N/M.\n"
        f"export const PREVIEW_IDS = {body};\n"
        f"export const CAPTURE_HOST = {json.dumps(doc.get('capture_host', ''))};\n"
        "export function idsFor(version) {\n"
        "  const out = {};\n"
        "  for (const [id, m] of Object.entries(PREVIEW_IDS))\n"
        "    out[id] = { counted: !!m.counted, stage: m.stage,\n"
        "                engine: (m.engine || {})[version] || [], req_ids: (m.req_ids || {})[version] || [] };\n"
        "  return out;\n"
        "}\n"
    )


def check_failures():
    want = render(load_map())
    if not OUT.exists():
        return ["functions/api/preview_ids.js missing — run gen_preview_ids.py --write"]
    if OUT.read_text(encoding="utf-8") != want:
        return ["functions/api/preview_ids.js differs from the id map projection — run gen_preview_ids.py --write"]
    return []


def main(argv):
    if "--write" in argv:
        OUT.write_text(render(load_map()), encoding="utf-8")
        print(f"preview-ids: wrote {OUT.relative_to(ROOT)}"); return 0
    fails = check_failures()
    for f in fails:
        print(f"  x {f}")
    print("preview-ids: " + ("in sync" if not fails else "OUT OF SYNC"))
    return 0 if not fails else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
