#!/usr/bin/env python3
"""
gen_known_issues.py — the KNOWN ISSUES page is a PROJECTION of one file (SITE-R-033, D5-12,
PLAN-v3 §2.13): conformance/ci/known_issues.json (validated by validate_known_issues.py) is the
only source of

    public/known-issues.json     rows + recomputed summary counts (the tracker binds to these)
    public/known-issues.html     one card per row, id="KI-###", symptom verbatim, repro, per-cut status
    site_claims.json KI-###      one REG claim per row (text = symptom, review_by = the row's clock)

Deterministic by construction: sorted iteration, no timestamps beyond the source's own
`generated` date, content derived only from the source. The validator runs FIRST and a red
validator (a refuted row, a stale re_verified, an unevidenced `fixed`, …) refuses to render
anything. `--check` regenerates into memory and byte-compares all three targets (site_gates.py
checkdocs, deploy.sh step 2 and the run_suite gate `known-issues-page` call it).

    python3 conformance/web/gen_known_issues.py --write    # (re)write the three targets
    python3 conformance/web/gen_known_issues.py --check    # `N rows · 0 refuted · 0 stale · schema OK · … in sync`
SPCK_PUBLIC points both modes at a scratch copy of public/. Stdlib only.
"""
import argparse
import collections
import datetime
import html
import importlib.util
import json
import os
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
PUB = pathlib.Path(os.environ.get("SPCK_PUBLIC", ROOT / "public"))
SRC = ROOT / "conformance" / "ci" / "known_issues.json"
JSON_NAME, HTML_NAME, CLAIMS_NAME = "known-issues.json", "known-issues.html", "site_claims.json"
PAGE_KEY = HTML_NAME


def _load_module(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def esc(s):
    return html.escape(str(s if s is not None else ""), quote=True)


def load_source(today=None):
    """(doc, validator_failures). The validator (schema referee included when jsonschema is
    installed) gates generation — nothing renders from a document it rejects."""
    doc = json.load(open(SRC, encoding="utf-8"))
    val = _load_module("validate_known_issues", ROOT / "conformance" / "ci" / "validate_known_issues.py")
    fails = val.validate_doc(doc, today or datetime.date.today(), val.ledger_row_ids())
    return doc, fails


# ── projections ──────────────────────────────────────────────────────────────
def summary(rows):
    def has(r, st):
        return any(c.get("status") == st for c in r.get("status_by_cut") or [])
    by_artifact = collections.Counter(r["artifact"] for r in rows)
    by_origin = collections.Counter(r["origin"] for r in rows)
    dates = sorted(r["re_verified"] for r in rows)
    return {
        "rows": len(rows),
        "refuted": sum(1 for r in rows if r.get("refuted") is not False),
        "open_on_some_cut": sum(1 for r in rows if has(r, "open")),
        "fixed_on_some_cut": sum(1 for r in rows if has(r, "fixed")),
        "unfixed_everywhere": sum(1 for r in rows if not has(r, "fixed")),
        "by_artifact": dict(sorted(by_artifact.items())),
        "by_origin": dict(sorted(by_origin.items())),
        "latest_re_verified": dates[-1] if dates else None,
        "oldest_re_verified": dates[0] if dates else None,
        "re_verified_window_days": 30,
    }


def render_json(doc):
    rows = sorted(doc["issues"], key=lambda r: r["id"])
    out = {
        "_about": "spck.dev KNOWN ISSUES — generated by conformance/web/gen_known_issues.py from "
                  "conformance/ci/known_issues.json (the single source, validated by "
                  "validate_known_issues.py: refuted rows never exist there, re_verified <= 30 days, "
                  "every `fixed` cut names its evidence). Never hand-edited; byte-compared by "
                  "site_gates.py checkdocs. Per-cut status comes from D4-05/D4-06 runs only.",
        "source": "conformance/ci/known_issues.json",
        "generated": doc["generated"],
        "spec_pin": doc["spec_pin"],
        "spec_pin_short": doc["spec_pin"][:8],
        "summary": summary(rows),
        "issues": rows,
    }
    return json.dumps(out, indent=2, ensure_ascii=True) + "\n"


def _status_chip(st):
    cls = {"open": "st-open", "fixed": "st-fixed", "not-applicable": "st-na"}.get(st, "")
    return f'<span class="st {cls}">{esc(st)}</span>'


def render_row(r):
    cuts = "".join(
        f'<li>{_status_chip(c["status"])} <span class="cut">{esc(c["cut"])}</span>'
        + (f' <span class="ev">— {esc(c["evidence"])}</span>' if c.get("evidence") else "") + "</li>"
        for c in r["status_by_cut"])
    filed = "".join(f'<li><a href="{esc(u)}" rel="noopener">{esc(u.replace("https://github.com/", ""))}</a></li>'
                    for u in r.get("filed") or [])
    filed_block = f'<dt>Filed</dt><dd><ul class="filed">{filed}</ul></dd>' if filed else '<dt>Filed</dt><dd>not yet filed</dd>'
    rp = r["repro"]
    return f'''<article class="ki" id="{esc(r["id"])}">
<h2><a class="rid" href="#{esc(r["id"])}">{esc(r["id"])}</a> <span class="chip">{esc(r["artifact"])}</span> <span class="comp">{esc(r["component"])}</span></h2>
<p class="symptom">{esc(r["symptom"])}</p>
<dl class="meta">
<dt>Reproduce</dt><dd><code class="cmd">{esc(rp["command"])}</code><div class="eo"><span class="k">expected</span> {esc(rp["expected"])}</div><div class="eo"><span class="k">observed</span> {esc(rp["observed"])}</div></dd>
<dt>Status by cut</dt><dd><ul class="cuts">{cuts}</ul></dd>
{filed_block}
<dt>Provenance</dt><dd>origin {esc(r["origin"])} · confidence {esc(r["confidence"])} · re-verified {esc(r["re_verified"])} · review by {esc(r["review_by"])} · ledger row {esc(r["ledger_row"])}</dd>
</dl>
</article>
'''


def render_html(doc):
    rows = sorted(doc["issues"], key=lambda r: r["id"])
    sm = summary(rows)
    pin = doc["spec_pin"]
    by_art = " · ".join(f"{esc(k)} {v}" for k, v in sm["by_artifact"].items())
    cards = "".join(render_row(r) for r in rows)
    body = f'''<header class="page-head">
  <div class="eyebrow">Known issues</div>
  <h1>Defects we have reproduced in the UCP reference stack</h1>
  <p class="sub">Each row is a defect in a published artifact around the specification — an SDK, a sample,
the official conformance suite, our own golden server — with a command you can run, what the pinned spec
text expects, what the artifact does, and the status on each released cut. Rows are re-verified within
thirty days and carry a review date; a finding that was refuted is removed from this file rather than
labeled. Source of truth: <code>conformance/ci/known_issues.json</code> in the
<a href="https://github.com/vishkaty/ucp-conformance" rel="noopener">repository</a>, validated in CI.</p>
</header>
<div class="stats">
  <div class="stat"><div class="n" data-live="known-issues.json:$.summary.rows">{sm["rows"]}</div><div class="l">issues tracked</div></div>
  <div class="stat"><div class="n" data-live="known-issues.json:$.summary.open_on_some_cut">{sm["open_on_some_cut"]}</div><div class="l">open on a published cut</div></div>
  <div class="stat"><div class="n" data-live="known-issues.json:$.summary.fixed_on_some_cut">{sm["fixed_on_some_cut"]}</div><div class="l">fixed on an upstream main</div></div>
  <div class="stat"><div class="n" data-live="known-issues.json:$.summary.unfixed_everywhere">{sm["unfixed_everywhere"]}</div><div class="l">no fix anywhere yet</div></div>
</div>
<p class="note">By artifact: {by_art}. Spec pin <code data-live="known-issues.json:$.spec_pin_short">{esc(pin[:8])}</code>
(2026-08-25). Latest re-verification <span data-live="known-issues.json:$.summary.latest_re_verified">{esc(sm["latest_re_verified"])}</span>.
Machine-readable: <a href="/known-issues.json">known-issues.json</a>.</p>
{cards}'''
    title = "Known issues in the UCP reference stack — reproducible, per cut | spck.dev"
    desc = (f"{sm['rows']} reproduced defects in the published UCP SDKs, samples, conformance suite and "
            f"reference servers, with the command to reproduce each and its status per released cut.")
    return _page(title, desc, body)


def _page(title, description, body):
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{esc(title)}</title>
<meta name="description" content="{esc(description)}">
<link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'><rect width='32' height='32' rx='6' fill='%23059669'/><text x='16' y='22' text-anchor='middle' fill='white' font-family='system-ui' font-weight='700' font-size='16'>S</text></svg>">
<link rel="stylesheet" href="/site.css">
<script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{{"token": "3bebef55335e4229a5c7807ce207fa13"}}'></script>
<style>
  .wrap {{ max-width:860px; margin:0 auto; padding:40px 24px 8px; }}
  .wrap h1 {{ font-size:clamp(24px,4vw,32px); font-weight:800; letter-spacing:-.8px; margin:0 0 10px; color:var(--ink); }}
  .wrap .sub {{ color:var(--muted); margin:0 0 24px; font-size:15px; line-height:1.65; max-width:700px; }}
  .stats {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:12px; margin:8px 0 14px; }}
  .stat {{ border:1px solid var(--border); border-radius:12px; padding:14px; }}
  .stat .n {{ font-size:26px; font-weight:800; letter-spacing:-.5px; color:var(--ink); }}
  .stat .l {{ font-size:12.5px; color:var(--muted); margin-top:2px; }}
  .note {{ font-size:13px; color:var(--muted); line-height:1.6; margin:10px 0 0; }}
  .ki {{ border:1px solid var(--border); border-radius:14px; padding:18px 20px; margin:22px 0; }}
  .ki h2 {{ font-size:17px; font-weight:800; letter-spacing:-.3px; margin:0 0 8px; color:var(--ink); display:flex; flex-wrap:wrap; gap:8px; align-items:center; }}
  .ki .rid {{ font-family:ui-monospace,monospace; font-size:14px; }}
  .ki .comp {{ font-weight:500; color:var(--muted); font-size:14px; }}
  .chip {{ display:inline-block; padding:2px 9px; border-radius:999px; font-size:12px; border:1px solid var(--muted); color:var(--muted); }}
  .symptom {{ font-size:15px; line-height:1.6; margin:0 0 12px; color:var(--ink); }}
  .meta {{ display:grid; grid-template-columns:120px 1fr; gap:8px 14px; font-size:14px; margin:0; }}
  .meta dt {{ color:var(--muted); }}
  .meta dd {{ margin:0; color:var(--ink); min-width:0; }}
  .cmd {{ display:block; white-space:pre-wrap; word-break:break-word; font-size:12.5px; padding:8px 10px; border-radius:8px; background:var(--card,rgba(5,150,105,.05)); }}
  .eo {{ font-size:13.5px; margin-top:6px; line-height:1.5; }}
  .eo .k {{ font-family:ui-monospace,monospace; font-size:12px; color:var(--muted); margin-right:6px; }}
  .cuts, .filed {{ list-style:none; padding:0; margin:0; }}
  .cuts li {{ margin:4px 0; line-height:1.5; }}
  .st {{ display:inline-block; font-size:11.5px; font-weight:700; padding:1px 8px; border-radius:999px; border:1px solid var(--border); margin-right:4px; }}
  .st-open {{ color:#b45309; border-color:#f59e0b; }}
  .st-fixed {{ color:var(--primary); border-color:var(--primary); }}
  .cut {{ font-family:ui-monospace,monospace; font-size:12.5px; }}
  .ev {{ color:var(--muted); font-size:13px; }}
  @media (max-width:560px) {{ .meta {{ grid-template-columns:1fr; }} }}
</style>
</head>
<body>
<nav class="site-nav"><a class="brand" href="/"><span class="mk">S</span>spck</a>
<div class="links"><a href="/check">Merchants</a><a href="/agent">Agents</a><a href="/coverage">Coverage</a><a href="/docs">Docs</a><a href="/state-of-ucp">State of UCP</a><a href="/known-issues">Known issues</a><a href="https://github.com/vishkaty/ucp-conformance" rel="noopener">GitHub ↗</a></div></nav>
<div class="wrap">
{body}
<footer class="page-foot"><p class="note">spck.dev is an independent, unofficial project — not affiliated with,
endorsed by, or a substitute for the official UCP conformance suite; the official suite is authoritative.
Issue rows describe our reproduction against pinned sources; the upstream projects are the authority on their own fixes.</p></footer>
</div>
</body>
</html>
"""


# ── site_claims KI-### projection ────────────────────────────────────────────
def claim_rows(doc):
    rows = sorted(doc["issues"], key=lambda r: r["id"])
    out = []
    for r in rows:
        cuts = "; ".join(f"{c['cut']}: {c['status']}" + (f" ({c['evidence']})" if c.get("evidence") else "")
                         for c in r["status_by_cut"])
        filed = ", ".join(r.get("filed") or []) or "not yet filed"
        out.append({
            "id": r["id"],
            "text": r["symptom"],
            "page": PAGE_KEY,
            "class": "REG",
            "evidence": (f"repro: {r['repro']['command']} -> expected: {r['repro']['expected']}; observed: "
                         f"{r['repro']['observed']}. status: {cuts}. filed: {filed}. ledger row "
                         f"{r['ledger_row']} (ops/GAP-LEDGER-0825.md), origin {r['origin']}, confidence "
                         f"{r['confidence']}, re-verified {r['re_verified']}; row validated by the run_suite "
                         f"'known-issues' gate; this claim is GENERATED by conformance/web/gen_known_issues.py "
                         f"from conformance/ci/known_issues.json"),
            "added": doc["generated"],
            "review_by": r["review_by"],
        })
    return out


def claims_synced(claims_doc, doc):
    """The claims register with its KI-### rows replaced by the projection (other rows untouched)."""
    out = json.loads(json.dumps(claims_doc))
    kept = [c for c in out.get("claims", []) if not (isinstance(c.get("id"), str) and c["id"].startswith("KI-"))]
    out["claims"] = kept + claim_rows(doc)
    return out


def _claims_serialize(doc):
    sync = _load_module("sync_site_claims", ROOT / "conformance" / "web" / "sync_site_claims.py")
    return sync.serialize(doc)


def targets(doc):
    """{relative path under public/: expected bytes} for the three projections."""
    claims_path = PUB / CLAIMS_NAME
    claims_doc = json.load(open(claims_path, encoding="utf-8")) if claims_path.exists() else {"claims": []}
    return {
        JSON_NAME: render_json(doc),
        HTML_NAME: render_html(doc),
        CLAIMS_NAME: _claims_serialize(claims_synced(claims_doc, doc)),
    }


def check_failures(today=None):
    """Failure strings (empty = in sync). Validator findings come first and stop the compare."""
    doc, vfails = load_source(today)
    if vfails:
        return [f"validator: {f}" for f in vfails] + ["refusing to render from a document the validator rejects"]
    fails = []
    for rel, want in targets(doc).items():
        f = PUB / rel
        if not f.exists():
            fails.append(f"public/{rel} missing — run gen_known_issues.py --write")
        elif f.read_text(encoding="utf-8") != want:
            fails.append(f"public/{rel} differs from regeneration (hand-edited or stale) — run gen_known_issues.py --write")
    return fails


def _stale(doc, today):
    n = 0
    for r in doc.get("issues") or []:
        try:
            n += (today - datetime.date.fromisoformat(r["re_verified"])).days > 30
        except (KeyError, ValueError):
            n += 1
    return n


def main(argv=None):
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    today = datetime.date.today()
    doc, vfails = load_source(today)
    rows = doc.get("issues") or []
    head = (f"known-issues page: {len(rows)} rows · "
            f"{sum(1 for r in rows if r.get('refuted') is not False)} refuted · {_stale(doc, today)} stale · "
            f"{'schema OK' if not vfails else 'schema RED'}")
    if vfails:
        for f in vfails:
            print(f"  x {f}")
        print(f"{head} · REFUSED — nothing rendered from a document the validator rejects")
        return 1
    if args.write:
        PUB.mkdir(parents=True, exist_ok=True)
        for rel, content in targets(doc).items():
            (PUB / rel).write_text(content, encoding="utf-8")
        print(f"{head} · wrote public/{JSON_NAME}, public/{HTML_NAME}, KI-* claims in public/{CLAIMS_NAME}")
        return 0
    fails = check_failures(today)
    for f in fails:
        print(f"  x {f}")
    print(f"{head} · " + (f"public/{JSON_NAME}, public/{HTML_NAME}, site_claims KI-* in sync" if not fails
                          else f"OUT OF SYNC ({len(fails)} target(s))"))
    return 0 if not fails else 1


if __name__ == "__main__":
    sys.exit(main())
