#!/usr/bin/env python3
"""
build_demo_data.py — the generator + freshness gate for the public interop demo
(`public/agent-demo.json`, rendered by `public/sandbox.html`).

The demo is powered by REAL runs of the reference agent against the adversarial sandbox —
never hand-authored. For a curated set of high-impact defects we boot the same sandbox the
kill-rate gate uses, run the conformant agent and the defective agent, capture both op-logs,
and record which agent check(s) flip to DEVIATION (with their req_ids + spec keyword).

Modes:
  build_demo_data.py            print the regenerated demo JSON to stdout
  build_demo_data.py --write    (re)write public/agent-demo.json
  build_demo_data.py --check    regenerate and assert the SHIPPED file is semantically in
                                sync with the live harness (freshness gate). Compares stable
                                fields only (defects, titles, catching id/req_ids/keyword/kills,
                                highlight kind, op counts) — per-run nonces/session-ids/ports
                                are normalized away, so this is deterministic. Exit 0 pass / 1 fail.

This closes two audit gaps at once: the demo is provably real (every case's catching check
still kills its defect) AND provably fresh (the shipped file matches what the harness produces).
"""
import json, os, sys, re
import urllib.parse as _up

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
PUBLIC_JSON = os.path.join(ROOT, "public", "agent-demo.json")
sys.path.insert(0, HERE)

import reference_agent  # noqa: E402
import agent_checks     # noqa: E402
import sandbox          # noqa: E402
from reference_agent import ReferenceAgent, DEFECTS  # noqa: E402

# curated, high-impact, human-legible failures that a schema-conformance check would MISS
CURATED = [
    ("skip_iss_validation", "OAuth Mix-Up / linking phishing",
     "The agent doesn't check that the authorization response came back from the same "
     "identity server it started with — so an attacker can splice in their own server and "
     "capture the user's linked account."),
    ("no_pkce", "Authorization-code interception",
     "The agent omits PKCE, so a stolen authorization code can be redeemed by an attacker "
     "who never had the user's session."),
    ("complete_on_mismatch", "Pays a total that doesn't add up",
     "The line items, tax and total don't reconcile, yet the agent completes the purchase "
     "autonomously instead of stopping for the buyer — a direct financial-harm path."),
    ("follow_error_description", "Follows a phishing decoy endpoint",
     "The agent trusts a URL embedded in an error message and authorizes at an "
     "attacker-named endpoint instead of the discovered one."),
    ("use_unavailable_instrument", "Pays with an instrument the merchant never offered",
     "The agent pays with a payment type that isn't in the merchant's advertised "
     "available_instruments — an unauthorized method."),
    ("skip_sig_verify", "Trusts an unverified merchant response",
     "The agent doesn't verify the merchant's RFC 9421 response signature, so a forged or "
     "tampered response is accepted as genuine."),
]

_ABOUT = ("Real recorded runs of the spck reference agent against the verified adversarial "
          "sandbox. Each case: a conformant agent vs an agent with one client-side defect, and "
          "the agent-side check that catches it. Per-run nonces (PKCE/state values, session ids) "
          "are normalized to presence markers so the shown difference is the defect, not "
          "randomness. Generated by the kill-rate harness — not hand-authored.")


def _salient_query(path):
    """Auth params that make OAuth defects visible. Per-run nonces become a stable
    presence marker so the diff is the defect, not randomness."""
    if not path or "?" not in path:
        return {}
    q = _up.parse_qs(path.split("?", 1)[1])
    keep = {}
    for k in ("response_type", "code_challenge_method", "scope"):
        if k in q:
            keep[k] = q[k][0]
    for k in ("code_challenge", "state"):
        if k in q and q[k][0]:
            keep[k] = "present"
    return keep


def _salient_body(op, body):
    if not isinstance(body, dict):
        return {}
    out = {}
    if op == "complete":
        insts = (((body.get("payment") or {}).get("instruments")) or [])
        types = [i.get("type") for i in insts if isinstance(i, dict)]
        if types:
            out["pays_with"] = ",".join(t for t in types if t)
        if "buyer" in body:
            out["buyer_sent"] = True
    if op == "create_checkout":
        li = body.get("line_items")
        out["line_items"] = len(li) if isinstance(li, list) else ("MISSING" if body else None)
        for k in ("id", "status", "totals", "discounts", "currency"):
            if k in body:
                out["sent_" + k] = True
    return {k: v for k, v in out.items() if v is not None}


def _slim(log):
    out = []
    for e in log:
        req = e.get("request") or {}
        resp = e.get("response") or {}
        flags = {k: v for k, v in e.items()
                 if k not in ("request", "response", "op") and not k.startswith("_")}
        path = req.get("path")
        cpath = path.split("?", 1)[0] if path else path
        if cpath:
            cpath = re.sub(r"http://127\.0\.0\.1:\d+", "{merchant}", cpath)
            cpath = re.sub(r"(chk|ord|sess)_[0-9a-f]+", r"\1_{id}", cpath)
        row = {"op": e.get("op"), "method": req.get("method"), "path": cpath,
               "status": resp.get("status"), "flags": flags}
        q = _salient_query(path)
        if q:
            row["query"] = q
        b = _salient_body(e.get("op"), req.get("body"))
        if b:
            row["body"] = b
        out.append(row)
    return out


def _highlight(clean, mut):
    if len(clean) != len(mut):
        stop = clean[-1] if clean else {}
        cont = mut[len(clean)] if len(mut) > len(clean) else {}
        return {"kind": "stopped",
                "clean": f"stopped safely after {len(clean)} ops (at {stop.get('op')})",
                "mutant": f"kept going — reached {cont.get('op')} ({len(mut)} ops)"}
    for i in range(len(clean)):
        c, m = clean[i], mut[i]
        for key in ("query", "body", "flags", "path", "status"):
            if c.get(key) != m.get(key):
                cv, mv = c.get(key), m.get(key)
                if key in ("query", "body", "flags"):
                    cv = {k: (c.get(key) or {}).get(k)
                          for k in set((c.get(key) or {})) | set((m.get(key) or {}))
                          if (c.get(key) or {}).get(k) != (m.get(key) or {}).get(k)}
                    mv = {k: (m.get(key) or {}).get(k) for k in cv}
                return {"kind": key, "op": c.get("op"), "clean": cv, "mutant": mv}
    return {"kind": "none", "clean": "", "mutant": ""}


def build():
    """Regenerate the demo dict from the live harness (deterministic after normalization)."""
    by_defect = {}
    for chk in agent_checks.CHECKS:
        by_defect.setdefault(chk.kill_mutation, []).append(chk)
    jwks = [ReferenceAgent.signing_jwk()]
    demo = {"_about": _ABOUT, "conformant": None, "cases": []}
    with sandbox.serve(agent_jwks=jwks) as (base, _srv):
        demo["conformant"] = _slim(ReferenceAgent(base).run_flow())
    for defect, title, why in CURATED:
        checks = by_defect.get(defect, [])
        if not checks:
            raise SystemExit(f"build_demo_data: no agent check has kill_mutation={defect!r}")
        scenario = checks[0].scenario
        with sandbox.serve(scenario=scenario, agent_jwks=jwks) as (base, _srv):
            clean_log = ReferenceAgent(base).run_flow()
            mut_log = ReferenceAgent(base, defect=defect).run_flow()
            catching = []
            for chk in checks:
                on_clean = chk.predicate(clean_log)
                on_mut = chk.predicate(mut_log)
                catching.append({"id": chk.id, "req_ids": chk.req_ids, "keyword": chk.keyword,
                                 "clean": on_clean, "mutant": on_mut,
                                 "kills": on_clean == agent_checks.CLEAN
                                 and on_mut == agent_checks.DEVIATION})
        sclean, smut = _slim(clean_log), _slim(mut_log)
        demo["cases"].append({"defect": defect, "title": title, "why": why,
                              "spec_desc": DEFECTS[defect], "scenario": scenario,
                              "clean": sclean, "mutant": smut,
                              "highlight": _highlight(sclean, smut), "catching": catching})
    return demo


def _stable(demo):
    """Projection compared by the freshness gate — the semantic fields, no random nonces."""
    return {
        "conformant_ops": len(demo.get("conformant") or []),
        "cases": [{
            "defect": c["defect"], "title": c["title"], "why": c["why"],
            "spec_desc": c["spec_desc"], "scenario": c["scenario"],
            "clean_ops": len(c["clean"]), "mutant_ops": len(c["mutant"]),
            "highlight": c["highlight"],
            "catching": [{"id": k["id"], "req_ids": k["req_ids"],
                          "keyword": k["keyword"], "kills": k["kills"]} for k in c["catching"]],
        } for c in demo.get("cases", [])],
    }


def check():
    """Freshness gate: shipped file exists, every case's check kills, and it matches a fresh build."""
    if not os.path.exists(PUBLIC_JSON):
        print(f"demo gate: FAIL — {PUBLIC_JSON} missing (run: build_demo_data.py --write)")
        return 1
    shipped = json.load(open(PUBLIC_JSON))
    fresh = build()
    problems = []
    # 1. every case's catching check must actually kill its defect (the demo's core claim)
    for c in fresh["cases"]:
        if not any(k["kills"] for k in c["catching"]):
            problems.append(f"case {c['defect']}: NO catching check kills it in the live harness")
    if len(fresh["cases"]) != len(CURATED):
        problems.append(f"expected {len(CURATED)} cases, harness produced {len(fresh['cases'])}")
    # 2. the shipped file must match a fresh build on the stable projection
    if _stable(shipped) != _stable(fresh):
        problems.append("public/agent-demo.json is STALE vs the harness — "
                        "regenerate: python3 conformance/agent/build_demo_data.py --write")
    if problems:
        print("demo gate: FAIL —")
        for p in problems:
            print("  -", p)
        return 1
    print(f"demo gate: PASS — {len(fresh['cases'])} real cases, every catching check kills its "
          f"defect, shipped agent-demo.json is in sync with the harness.")
    return 0


def main():
    if "--check" in sys.argv:
        return check()
    demo = build()
    if "--write" in sys.argv:
        with open(PUBLIC_JSON, "w") as f:
            json.dump(demo, f, indent=1)
        print(f"wrote {PUBLIC_JSON} — {len(demo['cases'])} cases")
        return 0
    print(json.dumps(demo, indent=1))
    return 0


if __name__ == "__main__":
    sys.exit(main())
