#!/usr/bin/env python3
"""
run_compare.py — P2-13: FAIR, reproducible kill-rate comparison of the spck
conformance suite vs the OFFICIAL UCP conformance suite, on a COMMON mutant set.

What it proves (and only this): for each injected MUST-defect in mutants.json —
defects a conformant server would never emit, injected by sticky_proxy.py in
front of the pinned flower golden — does each suite, run exactly as a merchant
would run it, AFFIRMATIVELY report the server non-conformant?

Fairness rules (enforced here, not just promised):
  * Both suites talk to the SAME mutated server (same proxy URL, same defect,
    no cooperation headers). Baselines run through the same proxy in
    passthrough mode, so the network path is identical in every condition.
  * EVERY suite run gets a freshly booted, freshly reseeded golden (identical
    pinned seed state). Not a convenience: the flower reference DEPLETES
    INVENTORY on every completed checkout, so a long-lived golden eventually
    answers every create with 400 OUT_OF_STOCK and mass-fails whichever suite
    runs later — and even short of exhaustion, a shared long-lived server
    means the second suite always faces a more-depleted state than the first.
    A fresh golden per suite run removes the whole class.
  * The official suite runs AS-CONFIGURED by its own repo (its flower-shop
    conformance_input + fixtures, full `pytest` run — never a filtered subset).
    Our suite runs AS-SHIPPED (merchant.py) with our canonical flower config
    (REF_CONFIG from validate_merchant_checks.py) — no comparison-specific
    checks, no comparison-specific config.
  * CATCH is symmetric and strict: the suite's own normal report must signal
    non-conformance —
      official: >=1 test newly failing/erroring vs its clean-golden baseline
                (tests unstable across baseline runs are excluded from
                catch credit entirely);
      spck:     >=1 MUST reported as a deviation (aggregate goes red). A run
                that merely degrades to not-tested/incomplete is a MISS for us.
      A harness/runner crash is NEVER a catch — it is flagged for review.
  * Only `shared_surface: true` mutants enter the head-to-head. Mutants on
    surfaces the official suite does not attempt are reported separately and
    never blended into the headline numbers.
  * Determinism: every mutant is run --repeat times (default 2) for each suite;
    a mutant only counts as CAUGHT by a suite if EVERY repeat catches it, and
    disagreement is flagged in the results.

Usage (see README.md for the full reproduction script):
    python3 run_compare.py [--golden-port 8290] [--proxy-port 8291]
        [--repeat 2] [--only id1,id2] [--out results/]
Exit 0 = comparison completed (whatever the numbers say); nonzero = harness error.
"""
import argparse, json, os, pathlib, re, shutil, socket, subprocess, sys, tempfile, time
import urllib.request
try:                                   # junit files here are locally generated by
    import defusedxml.ElementTree as ET     # pytest, but parse defensively anyway
except ImportError:                    # (defusedxml is optional; stdlib fallback)
    import xml.etree.ElementTree as ET

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[1]
SELF = ROOT / "conformance" / "selfcheck"
CHECKS = ROOT / "conformance" / "checks"
OFFICIAL_DIR = HERE / ".official" / "conformance"
PYSDK_DIR = HERE / ".official" / "python-sdk"


# --------------------------------------------------------------------------- #
#  pure logic (unit-tested in test_compare.py)                                #
# --------------------------------------------------------------------------- #
def decide_catch_official(baseline_unstable, baseline_failed, run_failed, crashed):
    """Newly failing/erroring tests, minus anything unstable on the clean golden."""
    if crashed:
        return False, []
    new = sorted((set(run_failed) - set(baseline_failed)) - set(baseline_unstable))
    return bool(new), new


def decide_catch_spck(baseline_deviations, run_deviations, crashed):
    """>=1 MUST deviation the clean-golden baseline did not have."""
    if crashed:
        return False, []
    new = sorted(set(run_deviations) - set(baseline_deviations))
    return bool(new), new


def compute_rates(mutants, records):
    """records: {mutant_id: {"spck_catch": bool, "official_catch": bool}}.
    Head-to-head covers ONLY shared_surface mutants. Non-shared mutants go to
    the addendum. `diagnostic: true` mutants are counted NOWHERE — they are
    measured purely for transparency (e.g. defects excluded from the common
    set because the violated requirement binds the platform, not the server)."""
    mutants = [m for m in mutants if not m.get("diagnostic")]
    shared = [m for m in mutants if m.get("shared_surface")]
    only = [m for m in mutants if not m.get("shared_surface")]
    out = {
        "shared_surface": {
            "n": len(shared),
            "spck_caught": sum(1 for m in shared if records[m["id"]]["spck_catch"]),
            "official_caught": sum(1 for m in shared if records[m["id"]]["official_catch"]),
        },
        "spck_only_surface": {
            "n": len(only),
            "spck_caught": sum(1 for m in only if records[m["id"]]["spck_catch"]),
            "official_caught": sum(1 for m in only if records[m["id"]]["official_catch"]),
        },
    }
    for k in out:
        n = out[k]["n"]
        out[k]["spck_rate"] = round(out[k]["spck_caught"] / n, 4) if n else None
        out[k]["official_rate"] = round(out[k]["official_caught"] / n, 4) if n else None
    return out


def validate_citations(mutants, register_dir):
    """Every cited requirement id must exist in the pinned register as MUST/MUST NOT."""
    rows = {}
    for f in sorted(pathlib.Path(register_dir).glob("*.json")):
        d = json.loads(f.read_text())
        items = d if isinstance(d, list) else d.get("requirements", d.get("rows", []))
        for r in items:
            rows[r["id"]] = r
    problems = []
    for m in mutants:
        for cid in m["citations"]:
            r = rows.get(cid)
            if r is None:
                problems.append(f"{m['id']}: cites {cid} which is not in the register")
            elif (r.get("keyword") not in ("MUST", "MUST NOT", "REQUIRED")
                  and not m.get("diagnostic")):
                # diagnostic mutants exist precisely because their citation is
                # NOT a server MUST (platform-binding / MAY); everything that
                # counts anywhere must cite a MUST.
                problems.append(f"{m['id']}: cites {cid} which is {r.get('keyword')}, not a MUST")
    return problems, rows


# --------------------------------------------------------------------------- #
#  process management                                                         #
# --------------------------------------------------------------------------- #
def _port_free(port):
    with socket.socket() as s:
        return s.connect_ex(("127.0.0.1", port)) != 0


class Golden:
    """Boots a FRESH pinned golden (reseeded to the identical initial state)
    before every suite run — see the fairness rules in the module docstring."""

    def __init__(self, port, sim_secret, db_dir):
        self.port, self.sim_secret, self.db_dir = port, sim_secret, db_dir
        self.url = f"http://localhost:{port}"

    def boot(self):
        # Wipe the databases so "identical pinned seed state" is literally true:
        # import_csv reseeds products/inventory/discounts, but checkout-session
        # and order rows in transactions.db would otherwise survive across boots.
        for db in pathlib.Path(self.db_dir).glob("*.db"):
            db.unlink(missing_ok=True)
        env = dict(os.environ, PORT=str(self.port), SIM_SECRET=self.sim_secret,
                   DB_DIR=self.db_dir)
        r = subprocess.run([str(ROOT / "conformance" / "ci" / "serve_golden.sh")],
                           env=env, capture_output=True, text=True, timeout=300)
        if r.returncode != 0:
            raise RuntimeError(f"golden boot failed:\n{(r.stderr or '')[-1500:]}")

    def stop(self):
        env = dict(os.environ, PORT=str(self.port), DB_DIR=self.db_dir)
        subprocess.run([str(ROOT / "conformance" / "ci" / "stop_golden.sh")],
                       env=env, capture_output=True, text=True, timeout=120)


def start_proxy(golden, port, mutant=None):
    args = [sys.executable, str(HERE / "sticky_proxy.py"),
            "--upstream", golden, "--port", str(port),
            "--rewrite", f"{golden}=http://localhost:{port}"]
    if mutant:
        args += ["--mutate", mutant["mutate"],
                 "--match-path", mutant["match"]["path"],
                 "--match-methods", mutant["match"].get("methods", "GET,POST,PUT,DELETE,PATCH"),
                 "--match-status", mutant["match"].get("status", "all")]
    p = subprocess.Popen(args, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    for _ in range(50):
        try:
            with urllib.request.urlopen(f"http://localhost:{port}/.well-known/ucp", timeout=2):
                return p
        except Exception:
            time.sleep(0.2)
    p.kill()
    raise RuntimeError(f"sticky proxy failed to become ready on :{port}")


def run_spck(server, config_path):
    """Run our as-shipped merchant runner; return (deviating_check_ids, meta).

    The ARBITER is the suite's own verdict gate: rep['verdict']['deviations']
    is the gate's MUST-deviation count (SHOULD/MAY advisories never reach it),
    and the stated catch rule is ">=1 MUST reported as a deviation — the gate's
    red". So: if the gate counts zero MUST deviations, nothing here is a catch,
    no matter which advisory checks flagged; if it counts >0, the deviating
    check ids are the evidence list. No re-derivation of keywords here — the
    gate already did that arbitration, identically for every merchant."""
    r = subprocess.run(
        [sys.executable, str(CHECKS / "merchant.py"), "--server", server,
         "--config", str(config_path), "--json"],
        capture_output=True, text=True, timeout=600)
    if r.returncode not in (0, 2):
        return None, {"crashed": True, "stderr": r.stderr[-2000:]}
    try:
        rep = json.loads(r.stdout)
    except json.JSONDecodeError:
        return None, {"crashed": True, "stderr": "unparseable runner output"}

    flagged = sorted(c["id"] for c in rep["checks"] if c["status"] == "deviation")
    devs = flagged if rep["verdict"]["deviations"] > 0 else []
    meta = {"crashed": False, "aggregate": rep["verdict"]["aggregate"],
            "deviation_musts": rep["verdict"]["deviations"],
            "musts_passed": rep["verdict"]["musts_passed"],
            "advisory_flags": [] if devs else flagged,
            "dev_req_ids": sorted({rid for c in rep["checks"]
                                   if c["status"] == "deviation" for rid in c["req_ids"]})}
    return devs, meta


def run_official(server, sim_secret):
    """Run the official suite exactly as its README prescribes (full pytest run)."""
    with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as tf:
        junit = tf.name
    env = dict(os.environ, SERVER_URL=server, SIMULATION_SECRET=sim_secret)
    r = subprocess.run(["uv", "run", "pytest", "-q", "--junitxml", junit],
                       cwd=OFFICIAL_DIR, env=env, capture_output=True, text=True,
                       timeout=1800)
    failed, counts = [], {"tests": 0, "failures": 0, "errors": 0, "skipped": 0}
    try:
        root = ET.parse(junit).getroot()
        for suite in root.iter("testsuite"):
            for k in counts:
                counts[k] += int(suite.get(k, 0) or 0)
        for tc in root.iter("testcase"):
            if tc.find("failure") is not None or tc.find("error") is not None:
                failed.append(f"{tc.get('classname')}.{tc.get('name')}")
    except (ET.ParseError, FileNotFoundError):
        return None, {"crashed": True, "stderr": r.stderr[-2000:] + r.stdout[-2000:]}
    finally:
        pathlib.Path(junit).unlink(missing_ok=True)
    crashed = counts["tests"] == 0    # collection error / no tests ran = harness problem
    return (None if crashed else sorted(failed)), {"crashed": crashed, **counts}


# --------------------------------------------------------------------------- #
#  report rendering                                                           #
# --------------------------------------------------------------------------- #
def render_md(results):
    m = results
    L = []
    L.append("# Kill-rate comparison — spck suite vs official UCP conformance suite\n")
    L.append(f"_Generated {m['meta']['timestamp']} · methodology + fairness rules: "
             f"see README.md in this directory. All numbers reproducible via "
             f"`reproduce.sh`._\n")
    L.append("## Pinned inputs\n")
    for k, v in m["meta"]["pins"].items():
        L.append(f"- **{k}**: `{v}`")
    b = m["baseline"]
    L.append("\n## Clean-golden baselines (through the same passthrough proxy)\n")
    L.append(f"- official: {b['official']['tests']} tests, "
             f"{b['official']['failures']} failed, {b['official']['errors']} errors, "
             f"{b['official']['skipped']} skipped"
             + (f" — unstable across baseline runs (excluded from catch credit): "
                f"{', '.join(b['official_unstable'])}" if b["official_unstable"] else
                " — stable across repeat baseline runs"))
    L.append(f"- spck: aggregate `{b['spck']['aggregate']}`, "
             f"{b['spck']['musts_passed']} applicable MUSTs clean-pass, "
             f"{b['spck']['deviation_musts']} deviations\n")
    L.append("## Per-mutant results (head-to-head = shared surface only)\n")
    L.append("| mutant | injected MUST-defect | spec MUST | shared? | spck | official | deterministic |")
    L.append("|---|---|---|---|---|---|---|")
    for r in m["mutants"]:
        spck = "**CATCH** — " + ", ".join(r["spck_new_deviations"][:4]) if r["spck_catch"] \
            else ("crash (not counted)" if r.get("spck_crashed") else "MISS")
        off = "**CATCH** — " + ", ".join(t.split(".")[-1] for t in r["official_new_failures"][:4]) \
            if r["official_catch"] else ("crash (not counted)" if r.get("official_crashed") else "MISS")
        det = "yes" if r["deterministic"] else "**NO — flagged**"
        surf = ("diagnostic — counted nowhere" if r.get("diagnostic")
                else ("Y" if r["shared_surface"] else "N — addendum"))
        L.append(f"| {r['id']} | {r['defect']} | {', '.join(r['citations'])} | "
                 f"{surf} | {spck} | {off} | {det} |")
    rt = m["rates"]["shared_surface"]
    L.append("\n## Head-to-head catch-rate (shared surface only)\n")
    L.append(f"- **spck suite: {rt['spck_caught']}/{rt['n']} "
             f"({round(100 * rt['spck_rate'])}%)**")
    L.append(f"- **official suite: {rt['official_caught']}/{rt['n']} "
             f"({round(100 * rt['official_rate'])}%)**")
    ro = m["rates"]["spck_only_surface"]
    L.append("\n## Addendum — surfaces only spck covers (NEVER counted in the head-to-head)\n")
    L.append(f"- {ro['spck_caught']}/{ro['n']} caught by spck; the official suite does not "
             f"attempt these surfaces, so no official number is claimed for them.")
    for r in m["mutants"]:
        if not r["shared_surface"] and not r.get("diagnostic"):
            L.append(f"  - {r['id']}: {r['defect']} ({', '.join(r['citations'])}) — "
                     f"{'caught' if r['spck_catch'] else 'MISSED'} by spck. "
                     f"{r.get('surface_note', '')}")
    diags = [r for r in m["mutants"] if r.get("diagnostic")]
    if diags:
        L.append("\n## Diagnostics — measured for transparency, counted NOWHERE\n")
        L.append("These defects were excluded from the common set because the "
                 "violated requirement binds the PLATFORM, not the server, in the "
                 "pinned register — but a skeptic deserves the measured outcome:")
        for r in diags:
            s = "CATCH" if r["spck_catch"] else \
                "no red (as the register prescribes: advisory at most)"
            o = "CATCH" if r["official_catch"] else "MISS"
            L.append(f"  - {r['id']}: {r['defect']} ({', '.join(r['citations'])}) — "
                     f"spck {s}, official {o}. {r.get('surface_note', '')}")
    misses = [r for r in m["mutants"] if r["shared_surface"] and not r["spck_catch"]]
    if misses:
        L.append("\n## Where WE missed (gaps in the spck suite — to fix)\n")
        for r in misses:
            L.append(f"- {r['id']}: {r['defect']} — "
                     + ("caught by the official suite; " if r["official_catch"] else "")
                     + "tracked as a spck-suite gap.")
    om = [r for r in m["mutants"] if r["shared_surface"] and not r["official_catch"]]
    if om:
        L.append("\n## Official-suite misses on the common set (candidate upstream test-gap filings)\n")
        for r in om:
            L.append(f"- {r['id']}: {r['defect']} ({', '.join(r['citations'])})")
    return "\n".join(L) + "\n"


# --------------------------------------------------------------------------- #
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--golden-port", type=int, default=8290)
    ap.add_argument("--db-dir", default="/tmp/ucp_p2cmp_golden")
    ap.add_argument("--proxy-port", type=int, default=8291)
    ap.add_argument("--sim-secret", default="selfcheck-secret")
    ap.add_argument("--repeat", type=int, default=2,
                    help="runs per suite per mutant; catch requires ALL repeats to catch")
    ap.add_argument("--baseline-repeat", type=int, default=2)
    ap.add_argument("--only", help="comma-separated mutant ids (debugging; final results must be a full run)")
    ap.add_argument("--out", default=str(HERE / "results"))
    args = ap.parse_args()

    spec = json.loads((HERE / "mutants.json").read_text())
    mutants = spec["mutants"]
    if args.only:
        keep = set(args.only.split(","))
        mutants = [m for m in mutants if m["id"] in keep]

    problems, _ = validate_citations(mutants, ROOT / "conformance" / "requirements" / "2026-04-08")
    if problems:
        print("CITATION PROBLEMS:\n  " + "\n  ".join(problems), file=sys.stderr)
        return 1

    # our canonical flower config — imported, not duplicated
    sys.path.insert(0, str(SELF)); sys.path.insert(0, str(CHECKS))
    from validate_merchant_checks import REF_CONFIG           # noqa: E402
    cfg_path = pathlib.Path(tempfile.gettempdir()) / "p2cmp_flower_config.json"
    cfg_path.write_text(json.dumps(REF_CONFIG, indent=2))

    if not OFFICIAL_DIR.is_dir():
        print(f"official suite not present at {OFFICIAL_DIR} — run fetch_official.sh", file=sys.stderr)
        return 1
    for port in (args.proxy_port, args.golden_port):
        if not _port_free(port):
            print(f"port {port} busy — refusing (same reasoning as serve_golden.sh)", file=sys.stderr)
            return 1

    # Provenance guard: results committed as THE results must be attributable to
    # a clean, reachable commit — "valid only for the pins in its meta block"
    # (README) is self-defeating if the pin is a dirty tree. Debug runs go to a
    # non-default --out; the default results/ requires a clean tree.
    tree_dirty = bool(subprocess.run(["git", "-C", str(ROOT), "status", "--porcelain"],
                                     capture_output=True, text=True).stdout.strip())
    if tree_dirty and pathlib.Path(args.out).resolve() == (HERE / "results").resolve():
        print("working tree is dirty — refusing to write the canonical results/ "
              "(commit first, or use --out elsewhere for a debug run)", file=sys.stderr)
        return 1

    golden = Golden(args.golden_port, args.sim_secret, args.db_dir)
    proxy_url = f"http://localhost:{args.proxy_port}"
    dirty = bool(subprocess.run(["git", "-C", str(ROOT), "status", "--porcelain"],
                                capture_output=True, text=True).stdout.strip())
    results = {"meta": {
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "pins": {
            "spck_repo": subprocess.run(["git", "-C", str(ROOT), "rev-parse", "HEAD"],
                                        capture_output=True, text=True).stdout.strip()
                         + ("+dirty" if dirty else ""),
            "official_conformance": subprocess.run(["git", "-C", str(OFFICIAL_DIR), "rev-parse", "HEAD"],
                                                   capture_output=True, text=True).stdout.strip(),
            "official_python_sdk": subprocess.run(["git", "-C", str(PYSDK_DIR), "rev-parse", "HEAD"],
                                                  capture_output=True, text=True).stdout.strip(),
            "golden_samples": json.loads((ROOT / "conformance" / "SOURCES.lock.json").read_text()
                                         )["reference_sample_server"]["commit"],
        },
        "repeat": args.repeat, "golden": golden.url,
        "fresh_golden_per_suite_run": True,
    }}

    def spck_on_fresh_golden(mutant=None):
        """One spck run against a freshly reseeded golden (through the proxy)."""
        golden.boot()
        p = start_proxy(golden.url, args.proxy_port, mutant)
        try:
            return run_spck(proxy_url, cfg_path)
        finally:
            p.kill(); p.wait(); golden.stop()

    def official_on_fresh_golden(mutant=None):
        """One official-suite run against a freshly reseeded golden (through the proxy)."""
        golden.boot()
        p = start_proxy(golden.url, args.proxy_port, mutant)
        try:
            return run_official(proxy_url, args.sim_secret)
        finally:
            p.kill(); p.wait(); golden.stop()

    # ---------------- baselines (passthrough proxy) ----------------
    # Both suites get the SAME baseline treatment: --baseline-repeat runs each,
    # anything red in some-but-not-all baseline runs is unstable and earns no
    # catch credit for that suite. (A single spck baseline would have meant no
    # spck check could ever be flagged flaky — a structural asymmetry.)
    print("== baseline (passthrough proxy; fresh golden per run) ==", flush=True)
    spck_runs = []
    for i in range(args.baseline_repeat):
        d, m = spck_on_fresh_golden()
        if d is None:
            print("spck baseline crashed:\n" + m.get("stderr", ""), file=sys.stderr)
            return 1
        spck_runs.append((d, m))
        print(f"  spck baseline #{i + 1}: aggregate={m['aggregate']} "
              f"musts_passed={m['musts_passed']} deviations={m['deviation_musts']}", flush=True)
    base_meta = spck_runs[0][1]
    base_devs = sorted(set.intersection(*(set(d) for d, _ in spck_runs)))
    spck_unstable = sorted(set.union(*(set(d) for d, _ in spck_runs)) - set(base_devs))
    off_runs = []
    for i in range(args.baseline_repeat):
        f, meta = official_on_fresh_golden()
        if f is None:
            print("official baseline crashed:\n" + meta.get("stderr", ""), file=sys.stderr)
            return 1
        off_runs.append((f, meta))
        print(f"  official baseline #{i + 1}: {meta['failures']} failed, "
              f"{meta['errors']} errors, {meta['skipped']} skipped of {meta['tests']}", flush=True)
    base_off_failed = sorted(set.intersection(*(set(f) for f, _ in off_runs)))
    unstable = sorted(set.union(*(set(f) for f, _ in off_runs)) - set(base_off_failed))
    results["baseline"] = {"spck": base_meta, "spck_deviations": base_devs,
                           "spck_unstable": spck_unstable,
                           "official": off_runs[0][1], "official_failed": base_off_failed,
                           "official_unstable": unstable}

    # ---------------- mutants ----------------
    out_mutants, records = [], {}
    for mu in mutants:
        print(f"== mutant {mu['id']} ({mu['mutate']}) ==", flush=True)
        s_catches, s_new, s_crashed = [], [], False
        o_catches, o_new, o_crashed = [], [], False
        for rep in range(args.repeat):
            devs, smeta = spck_on_fresh_golden(mu)
            if devs is None:
                s_crashed = True; s_catches.append(False)
            else:
                c, new = decide_catch_spck(sorted(set(base_devs) | set(spck_unstable)),
                                           devs, False)
                s_catches.append(c); s_new = new
            fails, ometa = official_on_fresh_golden(mu)
            if fails is None:
                o_crashed = True; o_catches.append(False)
            else:
                c, new = decide_catch_official(unstable, base_off_failed, fails, False)
                o_catches.append(c); o_new = new
            print(f"  repeat {rep + 1}: spck={'CATCH' if s_catches[-1] else 'miss'} "
                  f"official={'CATCH' if o_catches[-1] else 'miss'}", flush=True)
        rec = {
            "id": mu["id"], "defect": mu["defect"], "mutate": mu["mutate"],
            "citations": mu["citations"], "shared_surface": bool(mu.get("shared_surface")),
            "diagnostic": bool(mu.get("diagnostic")),
            "surface_note": mu.get("surface_note", ""),
            "spck_catch": all(s_catches), "spck_new_deviations": s_new,
            "spck_crashed": s_crashed,
            "official_catch": all(o_catches), "official_new_failures": o_new,
            "official_crashed": o_crashed,
            "deterministic": (len(set(s_catches)) == 1 and len(set(o_catches)) == 1),
        }
        out_mutants.append(rec)
        records[mu["id"]] = {"spck_catch": rec["spck_catch"],
                             "official_catch": rec["official_catch"]}
    results["mutants"] = out_mutants
    results["rates"] = compute_rates(mutants, records)

    out = pathlib.Path(args.out); out.mkdir(parents=True, exist_ok=True)
    (out / "results.json").write_text(json.dumps(results, indent=2) + "\n")
    (out / "results.md").write_text(render_md(results))
    rt = results["rates"]["shared_surface"]
    print(f"\nshared-surface head-to-head: spck {rt['spck_caught']}/{rt['n']} · "
          f"official {rt['official_caught']}/{rt['n']}")
    print(f"results written to {out}/results.json and results.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
