// GENERATED by conformance/web/gen_preview_ids.py from conformance/web/preview_parity.json
// (the add-only JS preview id map, PLAN-v3 §2.18 D5-11 / SITE-R-034). Do not edit: the parity
// gate byte-compares this file. Each preview id -> { stage, counted, engine{version: [ids]},
// req_ids{version: [ids]} }; `counted:false` rows render but never enter summary / badge N/M.
export const PREVIEW_IDS = {
  "catalog.empty_search": {
    "counted": true,
    "engine": {
      "2026-01-11": [
        "catalog.empty_search"
      ],
      "2026-01-23": [
        "catalog.empty_search"
      ],
      "2026-04-08": [
        "catalog.empty_search"
      ],
      "2026-08-25": [
        "catalog.empty_search"
      ]
    },
    "req_ids": {
      "2026-01-11": [
        "CAT-012"
      ],
      "2026-01-23": [
        "CAT-012"
      ],
      "2026-04-08": [
        "CAT-012"
      ],
      "2026-08-25": [
        "CAT-012"
      ]
    },
    "stage": "catalog"
  },
  "catalog.live_probes": {
    "counted": false,
    "engine": {},
    "marker": true,
    "note": "status marker (`not-tested`) emitted when the store gates catalog reads behind authentication \u2014 never a verdict, never counted",
    "req_ids": {},
    "stage": "catalog"
  },
  "catalog.lookup_inputs": {
    "counted": true,
    "engine": {
      "2026-01-11": [
        "catalog.lookup_inputs"
      ],
      "2026-01-23": [
        "catalog.lookup_inputs"
      ],
      "2026-04-08": [
        "catalog.lookup_inputs"
      ],
      "2026-08-25": [
        "catalog.lookup_inputs"
      ]
    },
    "req_ids": {
      "2026-01-11": [
        "CAT-017",
        "CAT-018"
      ],
      "2026-01-23": [
        "CAT-017",
        "CAT-018"
      ],
      "2026-04-08": [
        "CAT-017",
        "CAT-018"
      ],
      "2026-08-25": [
        "CAT-017",
        "CAT-018"
      ]
    },
    "stage": "catalog"
  },
  "catalog.search_shape": {
    "counted": true,
    "engine": {
      "2026-01-11": [
        "catalog.search_shape"
      ],
      "2026-01-23": [
        "catalog.search_shape"
      ],
      "2026-04-08": [
        "catalog.search_shape"
      ],
      "2026-08-25": [
        "catalog.search_shape"
      ]
    },
    "req_ids": {
      "2026-01-11": [
        "CAT-012"
      ],
      "2026-01-23": [
        "CAT-012"
      ],
      "2026-04-08": [
        "CAT-012"
      ],
      "2026-08-25": [
        "CAT-012"
      ]
    },
    "stage": "catalog"
  },
  "discovery.capabilities_object": {
    "counted": true,
    "engine": {
      "2026-01-11": [
        "discovery.reverse_domain_names"
      ],
      "2026-01-23": [
        "discovery.reverse_domain_names"
      ],
      "2026-04-08": [
        "profile.reverse_domain_names",
        "discovery.reverse_domain_names"
      ],
      "2026-08-25": [
        "discovery.reverse_domain_names"
      ]
    },
    "note": "was mis-cited DISC-001 at every version; DISC-001 is the reverse-domain rule only at 01-11/01-23 (OVR-001 at 04-08/08-25, where DISC-001 is the HTTPS rule). 2026-01-11 declares capabilities as an ARRAY of {name} entries (engine p_reverse_domain).",
    "req_ids": {
      "2026-01-11": [
        "DISC-001"
      ],
      "2026-01-23": [
        "DISC-001"
      ],
      "2026-04-08": [
        "OVR-001"
      ],
      "2026-08-25": [
        "OVR-001"
      ]
    },
    "stage": "discovery"
  },
  "discovery.content_type": {
    "counted": false,
    "engine": {},
    "note": "SHOULD (application/json) \u2014 report-only: rendered, never in the denominator; no engine MUST twin",
    "req_ids": {},
    "stage": "discovery"
  },
  "discovery.services_array": {
    "counted": true,
    "engine": {
      "2026-01-11": [
        "discovery.rest_endpoint"
      ],
      "2026-01-23": [
        "discovery.rest_endpoint"
      ],
      "2026-04-08": [
        "discovery.rest_endpoint"
      ],
      "2026-08-25": [
        "discovery.rest_endpoint"
      ]
    },
    "note": "was mis-cited DISC-007 at every version; the engine's own req_ids_map renumbers DISC-007 (01-era) to DISC-005 at 04-08/08-25 (PLAN-v3 says DISC-002, which is the no-redirect rule preview() enforces separately \u2014 the map follows the engine). 2026-01-11 services are an OBJECT with a `rest` member (engine p_rest_endpoint).",
    "req_ids": {
      "2026-01-11": [
        "DISC-007"
      ],
      "2026-01-23": [
        "DISC-007"
      ],
      "2026-04-08": [
        "DISC-005"
      ],
      "2026-08-25": [
        "DISC-005"
      ]
    },
    "stage": "discovery"
  },
  "discovery.version": {
    "counted": true,
    "engine": {
      "2026-01-11": [
        "discovery.version"
      ],
      "2026-01-23": [
        "discovery.version"
      ],
      "2026-04-08": [
        "profile.version_dated",
        "discovery.version"
      ],
      "2026-08-25": [
        "discovery.version"
      ]
    },
    "note": "at 04-08 the attributed twin profile.version_dated is version-locked (versions=V0408) and cannot fire on a non-dated version \u2014 the field it grades is the one the scoping reads \u2014 so the unscoped discovery.version (req_ids_map 04-08: []) is listed too; decided twins must agree",
    "req_ids": {
      "2026-01-11": [
        "DISC-013"
      ],
      "2026-01-23": [
        "DISC-013"
      ],
      "2026-04-08": [
        "OVR-010"
      ],
      "2026-08-25": [
        "OVR-010"
      ]
    },
    "stage": "discovery"
  }
};
export const CAPTURE_HOST = "https://capture.example";
export function idsFor(version) {
  const out = {};
  for (const [id, m] of Object.entries(PREVIEW_IDS))
    out[id] = { counted: !!m.counted, stage: m.stage,
                engine: (m.engine || {})[version] || [], req_ids: (m.req_ids || {})[version] || [] };
  return out;
}
